apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: incidenthub
type: Opaque
data:
  # "postgres" encodé en base64
  db-password: cG9zdGdyZXM=
  # "votre_super_secret_jwt_changez_moi_en_production_12345" encodé en base64
  jwt-secret: dm90cmVfc3VwZXJfc2VjcmV0X2p3dF9jaGFuZ2V6X21vaV9lbl9wcm9kdWN0aW9uXzEyMzQ1